version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: myapp_db

volumes:
  mongo_data:
