name: Компиляция плагина

on: [ push, workflow_dispatch ]

jobs:
  compile-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Подключение Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Настройка доступа
        run: chmod +x ./gradlew

      - name: Сборка плагина
        run: ./gradlew jar

      - name: Выгрузка артефакта
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/

      - name: Получение нового тега
        id: newtag
        run: |
          tag=$(cat src/main/resources/plugin.json | grep "version*" | cut -d ":" -f 2,3 | tr -d \"," ")
          echo '::set-output name=tag::'$tag

      - name: Проверка существования тега
        uses: mukunku/tag-exists-action@v1.1.0
        id: checkTag
        with: 
          tag: ${{ steps.newtag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Создание релиза
        id: release
        if: ${{ !steps.checkTag.outputs.exists }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.newtag.outputs.tag }}
          release_name: Release ${{ steps.newtag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Выгрузка релиза
        id: upload-release-asset
        if: ${{ !steps.checkTag.outputs.exists }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./build/libs/DarkdustryPlugin-${{ steps.newtag.outputs.tag }}.jar
          asset_name: DarkdustryPlugin-${{ steps.newtag.outputs.tag }}.jar
          asset_content_type: application/java-archive