name: Компиляция плагина

on: [ push, workflow_dispatch ]

jobs:
  compile-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Подключение Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Настройка доступа
        run: chmod +x ./gradlew

      - name: Сборка плагина
        run: ./gradlew jar

      - name: Выгрузка артефакта
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/

      - name: Получение нового тега
        id: newtag
        run: |
          tag=$(cat src/main/resources/plugin.json | grep "version*" | cut -d ":" -f 2,3 | tr -d \"," ")
          echo '::set-output name=tag::'$tag

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            *.jar